import { ChangeEvent, useMemo, useRef, useState } from 'react'
import type { AppData, Equipment, MaterialRequirement } from './types'
import { clearData, freshSample, loadData, normalize, saveData } from './storage'
import { aggregate, clamp, equipmentProgress, isComplete, keyOf, number, overallProgress, progress } from './utils'
import { setClientId } from './drive'
import { useDriveSync } from './useDriveSync'

type Tab = 'dashboard' | 'equipment' | 'materials' | 'settings'
const id = () => crypto.randomUUID()
const emptyMaterial = (): MaterialRequirement => ({ id: id(), name: '', required: 0, note: '' })
const emptyEquipment = (): Equipment => ({ id: id(), name: '새 무역선 장비', grade: '등급 미설정', materials: [emptyMaterial()] })

function Progress({ value }: { value: number }) { return <div className="progress"><i className={value === 100 ? 'done' : value >= 70 ? 'near' : ''} style={{ width: `${value}%` }} /><span>{value}%</span></div> }
function NumInput({ value, onChange }: { value: number; onChange: (v: number) => void }) { return <input className="num" type="number" min="0" value={value} onChange={e => onChange(clamp(e.target.valueAsNumber))} /> }

export default function App() {
  const [data, setData] = useState<AppData>(loadData)
  const [tab, setTab] = useState<Tab>('dashboard'); const [selected, setSelected] = useState(data.equipment[0]?.id || '')
  const [query, setQuery] = useState(''); const [hideDone, setHideDone] = useState(false); const [sort, setSort] = useState<'shortage' | 'progress' | 'name'>('shortage')
  const [notice, setNotice] = useState(''); const [confirmReset, setConfirmReset] = useState(false); const importRef = useRef<HTMLInputElement>(null)
  const update = (next: AppData) => { const stamped = { ...next, updatedAt: new Date().toISOString() }; setData(stamped); try { saveData(stamped); setNotice('저장됨') } catch (e) { setNotice(e instanceof Error ? e.message : '저장 실패') } }
  const replaceLocal = (next: AppData) => { setData(next); try { saveData(next); setNotice('Drive 데이터를 불러왔습니다.') } catch (e) { setNotice(e instanceof Error ? e.message : '저장 실패') } }
  const drive = useDriveSync(data, replaceLocal)
  const materials = useMemo(() => aggregate(data), [data]); const totalProgress = overallProgress(data)
  const setOwned = (name: string, value: number) => update({ ...data, inventory: { ...data.inventory, [keyOf(name)]: value } })
  const editEquipment = (equipment: Equipment) => update({ ...data, equipment: data.equipment.map(e => e.id === equipment.id ? equipment : e) })
  const deleteEquipment = (equipmentId: string) => { if (!confirm('이 장비를 삭제할까요?')) return; const next = data.equipment.filter(e => e.id !== equipmentId); update({ ...data, equipment: next }); setSelected(next[0]?.id || '') }
  const download = () => { const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `bdo-ship-materials-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(a.href) }
  const importData = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { update(normalize(JSON.parse(await file.text()))); setNotice('데이터를 가져왔습니다.') } catch (e) { setNotice(e instanceof Error ? `가져오기 실패: ${e.message}` : '가져오기 실패') } finally { event.target.value = '' } }
  const ordered = materials.filter(m => m.name.includes(query.trim()) && (!hideDone || m.progress < 100)).sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name, 'ko') : sort === 'progress' ? a.progress - b.progress : b.shortage - a.shortage)
  const completed = data.equipment.filter(e => isComplete(e, data.inventory)).length
  return <main>
    <header><div><p className="eyebrow">BLACK DESERT · TRADE SHIP</p><h1>무역선 파템 재료 관리</h1></div><div className="header-status"><button className={`drive-status ${drive.status}`} onClick={drive.status === 'disconnected' || drive.status === 'failed' ? drive.authorize : undefined}>{drive.status === 'disconnected' ? 'Google Drive 연결' : drive.status === 'connecting' ? 'Drive 연결 중…' : drive.status === 'synced' ? '● 동기화됨' : '● 동기화 실패'}</button><span className="save">{drive.lastSavedAt ? `Drive 저장 ${new Date(drive.lastSavedAt).toLocaleString('ko-KR')}` : notice || 'LocalStorage 자동 저장'}</span></div></header>
    <nav>{([['dashboard','대시보드'],['equipment','장비별 재료'],['materials','전체 재료'],['settings','데이터 관리']] as [Tab,string][]).map(([key,label]) => <button className={tab === key ? 'active' : ''} onClick={() => setTab(key)} key={key}>{label}</button>)}</nav>
    {tab === 'dashboard' && <section className="dashboard">
      <div className="hero"><div><p>전체 재료 진행률</p><strong>{totalProgress}%</strong><Progress value={totalProgress} /></div><div className="stat"><b>{completed}</b><span>/ {data.equipment.length} 완료 장비</span></div></div>
      <h2>부족 재료 TOP</h2><div className="top-list">{materials.filter(m => m.shortage).sort((a,b) => b.shortage-a.shortage).slice(0,5).map(m => <div key={m.key}><b>{m.name}</b><span>필요 {number(m.required)} · 보유 {number(m.owned)} · <em>부족 {number(m.shortage)}</em></span></div>)}{!materials.some(m=>m.shortage) && <p className="empty">부족한 재료가 없습니다. 모든 장비를 완성했어요!</p>}</div>
      <h2>장비 진행 현황</h2><div className="cards">{data.equipment.map(e => { const p = equipmentProgress(e, data.inventory); return <button className={`card ${p===100?'complete':''}`} key={e.id} onClick={() => { setSelected(e.id); setTab('equipment') }}><span>{e.grade}</span><h3>{e.name}</h3><Progress value={p} /><small>{p === 100 ? '재료 완료' : `${e.materials.length}개 재료 추적 중`}</small></button> })}{!data.equipment.length && <p className="empty">등록된 장비가 없습니다. 데이터 관리에서 장비를 추가하세요.</p>}</div>
    </section>}
    {tab === 'equipment' && <section><div className="equip-tabs">{data.equipment.map(e => <button className={selected === e.id ? 'active' : ''} onClick={() => setSelected(e.id)} key={e.id}>{e.name}</button>)}</div>{data.equipment.filter(e=>e.id===selected).map(e => <EquipmentView equipment={e} inventory={data.inventory} setOwned={setOwned} key={e.id} />)}{!data.equipment.length && <p className="empty">장비가 없습니다. 데이터 관리에서 추가하세요.</p>}</section>}
    {tab === 'materials' && <section><div className="toolbar"><input placeholder="재료명 검색" value={query} onChange={e=>setQuery(e.target.value)} /><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="shortage">부족량순</option><option value="progress">진행률순</option><option value="name">이름순</option></select><label><input type="checkbox" checked={hideDone} onChange={e=>setHideDone(e.target.checked)} /> 완료 재료 숨기기</label></div><MaterialTable materials={ordered} setOwned={setOwned} /></section>}
    {tab === 'settings' && <section className="settings"><div className="panel"><h2>장비 및 재료 편집</h2><p>장비명, 등급과 재료를 자유롭게 바꿀 수 있습니다. 같은 이름의 재료는 보유 수량을 공유합니다.</p>{data.equipment.map(e => <EquipmentEditor equipment={e} onChange={editEquipment} onDelete={()=>deleteEquipment(e.id)} key={e.id} />)}<button className="primary" onClick={() => { const e = emptyEquipment(); update({ ...data, equipment: [...data.equipment, e] }); setSelected(e.id) }}>+ 장비 추가</button></div><div className="panel manage"><h2>Google Drive 동기화</h2><p>앱 전용 Drive 저장소만 사용합니다. 내 Drive 파일 목록에는 보이지 않습니다.</p><label className="client-id">OAuth Client ID<input defaultValue={drive.clientId} placeholder="VITE_GOOGLE_CLIENT_ID 또는 Client ID" onBlur={e => { setClientId(e.target.value); setNotice('Client ID를 저장했습니다.') }} /></label><small>요청 범위: drive.appdata · Client Secret은 사용하지 않습니다.</small>{drive.status === 'disconnected' ? <button className="primary" onClick={drive.authorize}>Google Drive 연결</button> : <button onClick={drive.disconnect}>Drive 연결 해제</button>}{drive.error && <p className="sync-error">{drive.error}</p>}<p className="sync-time">상태: {drive.status === 'synced' ? '동기화됨' : drive.status === 'failed' ? '동기화 실패' : drive.status === 'connecting' ? '연결 중' : '연결 안 됨'}<br />마지막 Drive 저장: {drive.lastSavedAt ? new Date(drive.lastSavedAt).toLocaleString('ko-KR') : '없음'}</p></div><div className="panel manage"><h2>백업 및 초기화</h2><p>내보낸 JSON 파일로 다른 기기에서도 진행 상황을 이어갈 수 있습니다.</p><button onClick={download}>JSON 내보내기</button><button onClick={()=>importRef.current?.click()}>JSON 가져오기</button><input ref={importRef} type="file" accept="application/json" hidden onChange={importData} /><button onClick={()=>update(freshSample())}>샘플 데이터 복원</button><button className="danger" onClick={()=>setConfirmReset(true)}>모든 저장 데이터 초기화</button></div></section>}
    {confirmReset && <div className="modal"><div><h2>저장 데이터를 초기화할까요?</h2><p>브라우저에 저장된 진행 데이터가 삭제되고 샘플 데이터로 돌아갑니다. 이 작업은 되돌릴 수 없습니다.</p><button onClick={()=>setConfirmReset(false)}>취소</button><button className="danger" onClick={()=>{ clearData(); const next=freshSample(); update(next); setSelected(next.equipment[0]?.id||''); setConfirmReset(false); setNotice('초기화했습니다.') }}>초기화</button></div></div>}
    {drive.conflict && <div className="modal"><div><h2>Drive와 로컬 데이터가 다릅니다</h2><p>기본 권장: <b>{drive.conflict.newer === 'drive' ? '더 최근인 Drive 데이터' : '더 최근인 로컬 데이터'}</b>를 사용합니다. 선택한 쪽이 다른 저장소를 덮어씁니다.</p><p>로컬: {new Date(drive.conflict.local.updatedAt).toLocaleString('ko-KR')}<br />Drive: {new Date(drive.conflict.drive.updatedAt).toLocaleString('ko-KR')}</p><button className={drive.conflict.newer === 'drive' ? 'primary' : ''} onClick={()=>drive.resolveConflict('drive')}>Drive 데이터 사용</button><button className={drive.conflict.newer === 'local' ? 'primary' : ''} onClick={()=>drive.resolveConflict('local')}>로컬 데이터 사용</button></div></div>}
  </main>
}
function EquipmentView({ equipment, inventory, setOwned }: { equipment: Equipment; inventory: Record<string,number>; setOwned:(n:string,v:number)=>void }) { const p=equipmentProgress(equipment,inventory); return <><div className="section-title"><div><p>{equipment.grade}</p><h2>{equipment.name}</h2></div><Progress value={p}/></div><MaterialTable materials={equipment.materials.map(m=>({key:keyOf(m.name),name:m.name,required:m.required,owned:clamp(inventory[keyOf(m.name)]),shortage:Math.max(m.required-clamp(inventory[keyOf(m.name)]),0),progress:progress(clamp(inventory[keyOf(m.name)]),m.required),note:m.note,crowCoinPrice:m.crowCoinPrice}))} setOwned={setOwned} /></> }
function MaterialTable({ materials, setOwned }: { materials: ReturnType<typeof aggregate>; setOwned:(name:string,value:number)=>void }) { return <div className="table-wrap"><table><thead><tr><th>재료명</th><th>필요 수량</th><th>현재 보유 수량</th><th>부족 수량</th><th>진행률</th><th>수급 메모</th><th>까마귀 주화</th></tr></thead><tbody>{materials.map(m=><tr key={m.key}><td><b>{m.name}</b></td><td>{number(m.required)}</td><td><NumInput value={m.owned} onChange={v=>setOwned(m.name,v)} /></td><td className={m.shortage?'shortage':''}>{number(m.shortage)}</td><td><Progress value={m.progress}/></td><td>{m.note || '—'}</td><td>{m.crowCoinPrice === undefined ? '—' : number(m.crowCoinPrice)}</td></tr>)}{!materials.length&&<tr><td colSpan={7} className="empty">표시할 재료가 없습니다.</td></tr>}</tbody></table></div> }
function EquipmentEditor({ equipment, onChange, onDelete }: {equipment:Equipment;onChange:(e:Equipment)=>void;onDelete:()=>void}) { const edit=(patch:Partial<Equipment>)=>onChange({...equipment,...patch}); const editMat=(i:number,patch:Partial<MaterialRequirement>)=>edit({materials:equipment.materials.map((m,n)=>n===i?{...m,...patch}:m)}); return <details className="editor"><summary>{equipment.name} <span>{equipment.materials.length}개 재료</span></summary><div className="edit-grid"><label>장비명<input value={equipment.name} onChange={e=>edit({name:e.target.value})}/></label><label>단계/등급<input value={equipment.grade} onChange={e=>edit({grade:e.target.value})}/></label></div>{equipment.materials.map((m,i)=><div className="material-edit" key={m.id}><input placeholder="재료명" value={m.name} onChange={e=>editMat(i,{name:e.target.value})}/><NumInput value={m.required} onChange={v=>editMat(i,{required:v})}/><input placeholder="수급 메모" value={m.note} onChange={e=>editMat(i,{note:e.target.value})}/><input type="number" min="0" placeholder="까마귀 주화" value={m.crowCoinPrice ?? ''} onChange={e=>editMat(i,{crowCoinPrice:e.target.value===''?undefined:clamp(e.target.valueAsNumber)})}/><button className="icon danger" onClick={()=>edit({materials:equipment.materials.filter((_,n)=>n!==i)})}>×</button></div>)}<button onClick={()=>edit({materials:[...equipment.materials,emptyMaterial()]})}>+ 재료 추가</button><button className="danger" onClick={onDelete}>장비 삭제</button></details> }
